spring:
  application:
    name: clash-bot-service-k8s
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/clash-bot
aws:
  endpoint-configuration:
    url: http://host.docker.internal:4566
    signingRegion: us-east-1
riot:
  url: https://na1.api.riotgames.com
  api-key: ${RIOT_API_KEY}
  timeout: 30s
cloud:
  aws:
    stack:
      auto: false
logging:
  level:
    root: ERROR
    com.poss: INFO
