spring:
  application:
    name: clash-bot-service
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR
    com.poss: INFO
    org.springframework: ERROR
    org.springframework.data: TRACE
    org.springframework.data.mongodb: TRACE
