name: Tear Down Environment

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to tear down'
                required: true
                default: 'Feature'
                type: environment

jobs:
    spin-down-task:
        name: "Tear Down Clash Bot Docker Image in ECS"
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        environment: ${{ inputs.environment }}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-region: ${{ vars.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

            - name: Go mod tidy
              working-directory: CIScripts/
              run: ./spin-down-task.sh clash-bot-service

    tear-down-post-environment:
        name: "Deploy Clash Bot Docker Image to ECS"
        needs:
          - spin-down-task
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
          id-token: write
          contents: read
        
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4.2.2
    
          - name: Setup Go
            uses: actions/setup-go@v5.3.0
            with:
              go-version: '1.23.6'
    
          - name: Go mod tidy
            working-directory: ClashBot-Pulumi/post/
            run: go mod tidy
    
          - name: Setup AWS credentials
            uses: aws-actions/configure-aws-credentials@v4.1.0
            with:
              aws-region: ${{ vars.AWS_REGION }}
              role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
    
          - uses: pulumi/actions@v6.1.0
            with:
              command: destroy
              stack-name: pre
              work-dir: ClashBot-Pulumi/post/
            env:
              PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    deploy-infra:
        name: "Deploy Clash Bot preqrequisite Infrastructure"
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        environment: ${{ inputs.environment }}
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2

            - name: Setup Go
              uses: actions/setup-go@v5.3.0
              with:
                go-version: '1.23.6'

            - name: Go mod tidy
              working-directory: ClashBot-Pulumi/pre/
              run: go mod tidy

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-region: ${{ vars.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

            - uses: pulumi/actions@v6.1.0
              with:
                command: up
                stack-name: destroy
                work-dir: ClashBot-Pulumi/pre/
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}